name: Fitst workflow
on:
  workflow_dispatch:
  push:
    branches:
        - "main"

jobs:
    lab-job:
        runs-on: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'Hello DevOps'
            - name: Second Step
              run: echo 'This is second step'
            - name: Third Step
              run: echo 'This is third step'
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Start job
              run: echo 'second job'
